#!/bin/bash
tmux new-session -d -s session_name

tmux rename-window 'Deozoa'
tmux new-window -t session_name:1 -n 'RapaNui'
tmux new-window -t session_name:2 -n 'Moai' 
tmux new-window -t session_name:3 -n 'Home'  

tmux send-keys -t session_name:0 "cd ~/Documents/Deozoa" C-m
tmux send-keys -t session_name:1 "cd ~/Documents/Deozoa/rapanui" C-m
tmux send-keys -t session_name:2 "cd ~/Documents/moai-sdk" C-m
tmux send-keys -t session_name:3 "cd ~" C-m
tmux send-keys -t session_name:0 "clear" C-m
tmux send-keys -t session_name:1 "clear" C-m
tmux send-keys -t session_name:2 "clear" C-m
tmux send-keys -t session_name:3 "clear" C-m

tmux select-window -t session_name:0
tmux attach-session -t session_name
